version: '2.0'
services:
   host1:
       container_name: host1
       ports:
       - 8080:8080
       - 8180:8180
       - 8545:8545
       - 8546:8546
       - 30303:30303 
       image: parity/parity:stable
       user: root
       working_dir: /home/parity'
       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/1/password:/home/parity/password:ro
       - ./deployment/1/authority.toml:/home/parity/authority.toml:ro
       - ./deployment/1/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/1/key.priv:/home/parity/data/network/key
       - ./data/1:/home/parity/data
       command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data 
   host2:
       container_name: host2 
       image: parity/parity:stable
       user: root
       working_dir: /home/parity'
       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/2/password:/home/parity/password:ro
       - ./deployment/2/authority.toml:/home/parity/authority.toml:ro
       - ./deployment/2/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/2/key.priv:/home/parity/data/network/key
       - ./data/2:/home/parity/data
       command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data 
   monitor:
      image: buythewhale/ethstats_monitor
      volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
   dashboard:
      image: buythewhale/ethstats
      volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
      ports:
      - 3001:3000
volumes:
  myapp:
    #driver: local
    driver_opts:
      o: uid=1000,gid=1000
